# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment
image: continuumio/anaconda3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # - git clone https://semaphoreP@bitbucket.org/pyKLIP/pyklip.git pyklip
          - ls 
          - ls pyklip
          # - cd pyklip # move into repo base dir
          # - ls pyklip
          - ls pyklip/instruments
          - python setup.py develop
          - py.test

          #Coverage and Coverall hooking
          - pip install coverage
          - pip install coveralls
          - coverage run --source ./pyklip -m py.test
          - coverage combine
          # - coverage html
          - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls

# #Coverage and Coverall hooking
# language: python
# python:
#   - "2.6"
#   - "2.7"
# install:
#   - pip install coverage
#   - pip install coveralls 
# script:
#   - coverage run --source ./pyklip -m py.test
#   - coverage combine
#   - coverage html

# after_success:
#   - COVERALLS_REPO_TOKEN coveralls